### ISSUE TITLE
Server Submission - CashCash - Tips to make money online

### ISSUE THREAD

**Issue by CharlieOno** [RevoltSocial/lists#102]
### Server Name

CashCash

### Server Icon URL

https://autumn.revolt.chat/icons/mqB7P4fr_CdPkBYoG6WZIi-KkAAOj7dhd0o3wtXdUy

### Short Server Info

Money-making tips and tricks.

### Long Server Info

Give and pick advices to make money online.

How it works?
Giving good advices gives you a better rank where you can access to better channels. You start from "default" and you can rank up to "diamond". Diamond advices may be the best advices in the server.

Why should I share my advices?

Giving advices, let you access to other advices because you may rank up to get even better way to make money online.

### Add Tags

money, finances, development, cryptocurrencies, tips

### Server Owner

BusinessGirl

### Server Owner ID

01FH36B6A97YDSXQW6XD7RXT8J

### Invite URL

https://app.revolt.chat/invite/TRrDXzyC

**Comment by nerrixDE** [comment]
@CharlieOno is this about real investment?

**Comment by CharlieOno** [comment]
It could be investment or discounts, affiliations, development, freelance advices...
