### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by samuelXfrenchXengineer** [RevoltSocial/lists#118]
### Server Name

Les Français

### Server Icon URL

https://app.revolt.chat/server/01FJVH9G15AJWDPBY6K8E22JXY/channel/01FJVH9G15KT8M8HBQ1T11TN30

### Short Server Info

For chill

### Long Server Info

My server is a server for french, but i make a section for other languages. This server is only for chill, whitout problem racist, mysoginist...

### Add Tags

Chill, French, English

### Server Owner

Samcmoi (me)

### Server Owner ID

01FJVH4Z7F0X1HEESCT30615KZ

### Invite URL

https://app.revolt.chat/invite/cM8MFEYZ

**Comment by xMaxximum** [comment]
Server Icon URL isn't valid

**Comment by samuelXfrenchXengineer** [comment]
> Server Icon URL isn't valid

ok
