### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by hoodiedfella** [RevoltSocial/lists#125]
### Server Name

TF2 Emprium 

### Server Icon URL

https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette1.wikia.nocookie.net%2Ftf2informer%2Fimages%2F6%2F69%2FMann_co_supply_crate.png%2Frevision%2Flatest%3Fcb%3D20120424234408&f=1&nofb=1

### Short Server Info

A server for fellow TF2 Players and people who just want to have fun. 

### Long Server Info

TF2 Emporium is a server about the videogame Team Fortress 2. https://store.steampowered.com/app/440/Team_Fortress_2/
This is a place where TF2 fans can hang out and talk about the game. We're a welcoming and friendly community. Come & join us!

### Add Tags

TF2,Gaming,TeamFortress2,TeamFortress,Tf,teamfortress2,tf,Tf2,tf2

### Server Owner

Evanarrel

### Server Owner ID

01FM43YWG2BZW3XWPF863N8ENV

### Invite URL

https://app.revolt.chat/invite/VDRYP8QB

**Comment by xMaxximum** [comment]
the server icon url needs to be hosted under revolt.chat
