### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by RHeijmann** [RevoltSocial/lists#13]
### Server Name

The Dutch Revolt

### Server Icon URL

https://autumn.revolt.chat/icons/8JkMex9JpUIeGeNmYy8t8UH7hcESC0G6soRku2IMMl?max_side=256

### Short Server Info

The first Dutch community on Revolt!

### Long Server Info

Welcome to the Dutch Revolt! To gain more traction in the Netherlands, we want to present to you the first Revolt server where Dutch is the primary language.

**--- Dutch ---**
Zoek jij een leuke plek om met andere te praten die dezelfde taal spreken? Dan ben je hier aan het goede adres. We zijn een beginnende community en proberen samen een leuke en gezellige groep op te bouwen. Kom er nu bij. Je zult er geen spijt van krijgen 🙂 

### Add Tags

Dutch, Netherlands, Community, Nederlands, Gezellig, Gezelschap

### Server Owner

Rik

### Server Owner ID

01FC1HP5X609Y93A9TG9XV6VVX

### Invite URL

https://app.revolt.chat/invite/9emN0y48

**Comment by rik** [comment]
I'm probably not the @rik you want to tag.

**Comment by RHeijmann** [comment]
@rik I'm sorry for tagging you.
