### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by oOoKandiioOo** [RevoltSocial/lists#141]
### Server Name

Kandi's Hideout

### Server Icon URL

https://app.revolt.chat/invite/aFdxN1gd

### Short Server Info

Fun server for people to chill and chat

### Long Server Info

Fun, English-only (sorry for those who can't speak English at all or very well) server for people to chill and chat. I'm also looking for staff.

### Add Tags

lofi, anime, games, vocaloid,

### Server Owner

Kandi

### Server Owner ID

01FEHR71WYMW5RAQFZGM8YC78K

### Invite URL

https://app.revolt.chat/invite/ga0Wtmm9

**Comment by xMaxximum** [comment]
your server icon URL is actually an invite to the server and your invite URL is a different URL than the other one? 

Please submit an actual server icon URL
