### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by CorvusRex3** [RevoltSocial/lists#145]
### Server Name

The Fightory

### Server Icon URL

https://autumn.revolt.chat/icons/QeABYXpMpgOkhhatjcgQoQqpuEl-r36KnE1fekuhhs?max_side=256

### Short Server Info

Fighting Sports / Strength & Conditioning / Nutrition

### Long Server Info

Talk about MMA, Boxing, Kickboxing, Muay Thai, Sanda, Wrestling, Judo, BJJ & Sambo.
Talk about your trainings and ask for help about Strength, Conditioning, Nutrition & Psychology.

### Add Tags

Sport, Fighting, Martial Arts, MMA, Boxing, Kickboxing, Muay Thai, Sanda, Judo, Wrestling, BJJ, Sambo, Strength, Conditioning, Nutrition

### Server Owner

Corvus_Rex

### Server Owner ID

01FNEK6GSVCDNDZ13J45AAY02G

### Invite URL

https://app.revolt.chat/invite/tjrbTpev

**Comment by xMaxximum** [comment]
invite is invalid

**Comment by CorvusRex3** [comment]
I submitted again, thanks.
