### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by CorvusRex3** [RevoltSocial/lists#146]
### Server Name

The Fightory

### Server Icon URL

https://autumn.revolt.chat/icons/QeABYXpMpgOkhhatjcgQoQqpuEl-r36KnE1fekuhhs?max_side=256

### Short Server Info

Fighting Sports / Strength & Conditioning / Nutrition

### Long Server Info

Talk about MMA, Boxing, Kickboxing, Muay Thai, Sanda, Wrestling, Judo, BJJ & Sambo.
Talk about your trainings and ask for help about Strength, Conditioning, Nutrition & Psychology.
English/French

### Add Tags

sport, fighting, martial arts, mma, boxing, mma, kickboxing, muay thai, sanda, judo, wrestling, bjj, sambo, strength, conditioning, nutrition

### Server Owner

Corvus_Rex

### Server Owner ID

01FNEK6GSVCDNDZ13J45AAY02G

### Invite URL

https://app.revolt.chat/invite/tjrbTpev

**Comment by xMaxximum** [comment]
duplicate: https://github.com/RevoltSocial/lists/issues/145

I already approved it.
