### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by ClaudiWolf2056** [RevoltSocial/lists#149]
### Server Name

Chill Zone

### Server Icon URL

https://autumn.revolt.chat/attachments/Ou_eJ_2gIpBtan-FmGCRI7uFkjzfQxQCWbgp-QH7Lf/download.jpg

### Short Server Info

Un server en español! Ven y diviertete!

### Long Server Info

Hola! Buscas un server en donde hablar en Revolt y hablas español? Enhorabuena! Entra aqui y disfruta de un servidor en crecimiento! 

### Add Tags

Servers, Comunity, Peru, Chat, Español

### Server Owner

CW2056

### Server Owner ID

01FNYBHSR1C7N38C49560S41RT

### Invite URL

https://app.revolt.chat/invite/NK976cJf

**Comment by nerrixDE** [comment]
@ClaudiWolf2056 please upload the logo as revolt attachment URL

**Comment by ClaudiWolf2056** [comment]
oh ok, sorry

**Comment by ClaudiWolf2056** [comment]
> @ClaudiWolf2056 please upload the logo as revolt attachment URL

that's OK?

**Comment by nerrixDE** [comment]
@ClaudiWolf2056 no you need to upload it into a revolt channel and copy the attachment url

**Comment by ClaudiWolf2056** [comment]
ok ready, here it is

**Comment by ClaudiWolf2056** [comment]
@nerrixDE ok

**Comment by ClaudiWolf2056** [comment]
thanks!
