### ISSUE TITLE
Revolt En Español

### ISSUE THREAD

**Issue by CheemsGM** [RevoltSocial/lists#150]
### Server Name

Revolt En Español

### Server Icon URL

https://cdn.discordapp.com/attachments/893133702144598067/916075319969079326/200.gif

### Short Server Info

Server de Revolt Completamente En Español ! 

### Long Server Info

Únete a compartir con la comunidad de Revolt En Español

### Add Tags

Español, Spanish

### Server Owner

@CheemsGM 

### Server Owner ID

01FNWEK1BY9AV6Q9GMM7WM7KTZ

### Invite URL

https://app.revolt.chat/invite/tRY7S0Tj

**Comment by nerrixDE** [comment]
@CheemsGM you need to upload the logo into a rtevolt channel and copy the attachment id and not use a discord cdn link
