### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by RexorX1** [RevoltSocial/lists#153]
### Server Name

¿?

### Server Icon URL

https://cdn.discordapp.com/attachments/910680049735327804/910700012294512661/16d465bda9963877a9b78c0872a0aa0e.gif

### Short Server Info

Programming

### Long Server Info

¿? is an Argentine server dedicated to programmers who love the digital development of anything, be it web, games, software, etc.

### Add Tags

Programming, Programación, Desarrollo

### Server Owner

003

### Server Owner ID

01FNXQHESCJ3J85X94600Z191Z

### Invite URL

https://app.revolt.chat/invite/qgpSXZe5

**Comment by xMaxximum** [comment]
the server icon URL needs to be a revolt URL, so you have to upload the file on a revolt server and then use that link,
