### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by samumuted** [RevoltSocial/lists#154]
### Server Name

Microsoft Community

### Server Icon URL

https://i.pinimg.com/originals/91/92/1c/91921cec4f8a8cbe3d09e596e0659d81.png

### Short Server Info

A server to talk about Microsoft and its services, people who like to talk about technology and all that!

### Long Server Info

Welcome to the Microsoft Community!
We are a group for people who like to talk about Technology and about Microsoft and its services (Windows, Office, etc.)

### Add Tags

Gaming, Community, Windows, Microsoft, Office, Revolt, Microsoft Community

### Server Owner

samumuted

### Server Owner ID

01FNY0W7RQ64CTE14WYEYV0W89

### Invite URL

https://app.revolt.chat/invite/P0Qj0qTP

**Comment by xMaxximum** [comment]
server icon URL needs to be a file hosted on revolt servers
