### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by SP-Network** [RevoltSocial/lists#156]
### Server Name

Argentina

### Server Icon URL

https://autumn.revolt.chat/icons/_EGN7sFUqV_sg79z2tqRkIPoM8wLNWBxNONdC2Z168?max_side=256

### Short Server Info

A server where you can make friends and grow your community by inviting people on spam channels

### Long Server Info

♕ | Argentina ツ

Servidor con Tématica Socializar

╭ ┅ ┅ ┅ ┅ ┅ ┅キ₊Ofrecemos₊キ┅ ┅ ┅ ┅ ┅ ┅ ┅ ┅
┊⨯・ ੭ ︰Variedad de Canales De Voz y Entretenimiento
┊⨯・ ੭ ︰Hacemos alianzas
┊⨯・ ੭ ︰Staff Siempre Activo
┊⨯・ ੭ ︰Decoración Piola
┊⨯・ ੭ ︰Puedes Conocer Gente Nueva
┊⨯・ ੭ ︰Sistema de spam/join 4 join
┊⨯・ ੭ ︰Invitar a tu Amigo/a Para que Seamos Mas Grandes
╰┅ ┅ ┅ ┅ ┅ ┅ ┅ ┅ ┅ ┅ ┅┅ ┅ ┅ ┅ ┅ ┅ ┅ ┅ ┅

Buscamos Gente activa y buena onda ♡︎

Espero que puedan disfrutar.. 🧉

### Add Tags

Argentina, Español, Spanish, Spam, Join for join, J4J

### Server Owner

EnzooSP

### Server Owner ID

01FNXDFAW09DSZX7CVDT4B95A2

### Invite URL

https://app.revolt.chat/invite/hgArCGA6

**Comment by xMaxximum** [comment]
the server icon URL does not exist.

**Comment by SP-Network** [comment]
> 

https://autumn.revolt.chat/icons/_EGN7sFUqV_sg79z2tqRkIPoM8wLNWBxNONdC2Z168?max_side=256
