### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by linklloyd** [RevoltSocial/lists#158]
### Bot Name

Chillidog

### Short Explanation

Fun, Meme , Spanish

### Long Explanation

Es un bot en español con comando basados en RexBot y proximamente traera más comandos

Por el momento solo tiene
--Neko
--Say
--Wikipedia
--Avatar
--Create
--Help
--Ping
--NPM
--Eval

Pero como anteriormente se dijo habra mas!

### Invite Link

https://app.revolt.chat/bot/01FP09ETFXHBWB67TTKATX2P8D

### Support Link

https://app.revolt.chat/invite/WJS3KQXf

### Bot Icon URL

https://autumn.revolt.chat/avatars/7oLRapqyktJE6S6aC4n6kU_YiLDz95A02D2nw2w_X_

### Add Tags

Fun, Meme , Spanish

### Owner Name

ᗪᑌᔕT

### Owner ID

01FP07387P0G6ANH01KWV2XHWY

### Bot ID

01FP09ETFXHBWB67TTKATX2P8D

### Help Command

--help

### Bot Prefix

--

### Library

revolt.js

**Comment by xMaxximum** [comment]
bot icon URL needs to be from revolt (take the bot's icon URL with developer console) and the invite link for the bot doesn't work for me.

**Comment by linklloyd** [comment]
> bot icon URL needs to be from revolt (take the bot's icon URL with developer console) and the invite link for the bot doesn't work for me.

Sorry i forgot i have the bot in private and the url i will change it

**Comment by linklloyd** [comment]
Updated
