### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by SP-Network** [RevoltSocial/lists#160]
### Bot Name

Argentina

### Short Explanation

Multi propose bot with 10 commands

### Long Explanation

Argentina is a multipurpose bot, it has +10 commands and it is under development!

### Invite Link

https://app.revolt.chat/bot/01FP18CHAVNGTJ8DV72T34DT57

### Support Link

https://app.revolt.chat/invite/hgArCGA6

### Bot Icon URL

https://autumn.revolt.chat/avatars/VqJPBZhhglKs0od9OQ7emQXSxPv8YKK4IQAKsPKeG6?max_side=256

### Add Tags

Argentina, Español, Spanish, multi-purpose

### Owner Name

EnzooSP

### Owner ID

01FNXDFAW09DSZX7CVDT4B95A2

### Bot ID

01FP18CHAVNGTJ8DV72T34DT57

### Help Command

!help

### Bot Prefix

!

### Library

revolt.js

**Comment by xMaxximum** [comment]
bot is offline

**Comment by SP-Network** [comment]
> 

Im making updates and adding a VPS
