### ISSUE TITLE
Siempre Ayudando

### ISSUE THREAD

**Issue by matiaszalacain** [RevoltSocial/lists#162]
### Server Name

Promociones

### Server Icon URL

https://autum.revolt.chat/EED2646C-73C6-4674-9302-22746A197E5B

### Short Server Info

Te ayudamos a crecer en tus proyectos

### Long Server Info

Somos una comunidad, un grupo de seres humanos que tienen ciertos elementos en común, tales como el idioma, costumbres, valores, tareas, visión del mundo, edad, ubicación geográfica, estatus social o roles.
Promoción es un término que hace mención a la acción y efecto de promover. Este verbo, por su parte, refiere a iniciar o impulsar un proceso o una cosa; elevar a alguien a un cargo o empleo superior al que tenía; o tomar la iniciativa para realizar algo.

### Add Tags

Comunidad, Promociones, Recomendaciones y spam 

### Server Owner

MatiasZalacain 

### Server Owner ID

01FNXZTGVBX111D7PPDQEVJM8V

### Invite URL

https://app.revolt.chat/invite/7kfAdXMx

**Comment by xMaxximum** [comment]
server icon URL does not exist.
