### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by Yander991** [RevoltSocial/lists#164]
### Server Name

Fan Yandere ღ

### Server Icon URL

https://autum.revolt.chat/https://c.tenor.com/KWmk3axqWYcAAAAM/ayano-aishi-yandere-simulator.gif

### Short Server Info

Fans de yandere simulator ღ ♡ღ ♡

### Long Server Info

╭─────── Fan Yandere ღ ───────╮ 

★・・・・・・・・★・・・・・・・・★・・・・・・・・★・・・・・・・・★
𝖧𝗈𝗅𝖺! 👋 𝖳𝖾 𝗂𝗇𝗏𝗂𝗍𝖺𝗆𝗈𝗌 𝖺 𝖾𝗌𝗍𝖺́ 𝗉𝖾𝗊𝗎𝖾𝗇̃𝖺 𝖿𝖺𝗆𝗂𝗅𝗂𝖺 𝗊𝗎𝖾 𝗏𝖺 𝖼𝗋𝖾𝖼𝗂𝖾𝗇𝖽𝗈 𝗉𝗈𝖼𝗈 𝖺 𝗉𝗈𝖼𝗈, 𝗉𝗎𝖾𝖽𝖾𝗌 𝖼𝗈𝗇𝗈𝖼𝖾𝗋 𝖺 𝗀𝖾𝗇𝗍𝖾 𝗇𝗎𝖾𝗏𝖺 𝖾𝗇 𝖾𝗌𝗍𝖾 𝗌𝖾𝗋𝗏𝗂𝖽𝗈𝗋 𝗒 𝗉𝖺𝗌𝖺𝗋𝗅𝖺 𝗀𝖾𝗇𝗂𝖺𝗅 𝖼𝗈𝗇 𝗇𝗈𝗌𝗈𝗍𝗋𝗈𝗌, 𝗊𝗎𝖾 𝖾𝗌𝗉𝖾𝗋𝖺𝗌 𝗉𝖺𝗋𝖺 𝗎𝗇𝗂𝗋𝗍𝖾?! ¡𝖳𝖾 𝖾𝗌𝗉𝖾𝗋𝖺𝗆𝗈𝗌! 🥳
★・・・・・・・・★・・・・・・・・★・・・・・・・・★・・・・・・・・★

╔════════════◄••¿𝖰𝗎𝖾 𝗈𝖿𝗋𝖾𝖼𝖾𝗆𝗈𝗌?••►═════════════╗
║
╠『✨』Admins casi muy activos 
╠『🤗』Usuarios sociales y amigables.
╠『😁』Variedad de canales con diferentes temáticas.
╠『🎨』Servidor ordenado y configurado.
╠『🎁』Alianzas con otros servidores.
╠『😎』Canales de shitpost, videos, memes y más.
╠『👾』Canales de entretenimiento.
╠『💦』Contamos con canales NSFW. Con verificación 
╠『🤩』Únete para conocer mas acerca del servidor.
║
╚════════════◄••𝖤𝗌𝗉𝖾𝗋𝗈 𝗍𝖾 𝗀𝗎𝗌𝗍𝖾••►═════════════╝

### Add Tags

Yandere Simulator, BLOOD, Anime

### Server Owner

yander991

### Server Owner ID

01FP12ZYTB1HKPF6H4671QZ52N

### Invite URL

https://app.revolt.chat/invite/BrWkAyvz

**Comment by xMaxximum** [comment]
server icon URL does not exist. You have to upload the file in a revolt channel then copy the URL to that attachment
