### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by a1g2sto** [RevoltSocial/lists#165]
### Bot Name

club

### Short Explanation

bot de Moderation

### Long Explanation

bot de Moderation

### Invite Link

https://app.revolt.chat/bot/01FNYTZV2VNQ7A3KQEBAQ6K2F6

### Support Link

https://app.revolt.chat/invite/j1pN3E6x

### Bot Icon URL

https://www.google.com/url?sa=i&url=https%3A%2F%2Ffondosmil.com%2Fdiscoteca&psig=AOvVaw1IQsDzE_yYqHjdrpa-UXYg&ust=1638797779597000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCNCam77jzPQCFQAAAAAdAAAAABAD

### Add Tags

Anime Moderation 

### Owner Name

Agus

### Owner ID

01FNYJV3S0G1FY0TQC0RTQ6K05

### Bot ID

01FNYTZV2VNQ7A3KQEBAQ6K2F6

### Help Command

;help

### Bot Prefix

;

### Library

qqq

**Comment by xMaxximum** [comment]
bot icon URL needs to be an URL of an image that's hosted on revolt
