### ISSUE TITLE
Submit Server

### ISSUE THREAD

**Issue by a1g2sto** [RevoltSocial/lists#166]
### Server Name

Los Raros Club

### Server Icon URL

https://app.revolt.chat/invite/EMR4R0yD

### Short Server Info

server community

### Long Server Info

server community

### Add Tags

community

### Server Owner

agus

### Server Owner ID

01FNYJV3S0G1FY0TQC0RTQ6K05

### Invite URL

https://app.revolt.chat/invite/zeSQ9xh6

**Comment by xMaxximum** [comment]
server icon URL is not a valid image/gif,
