### ISSUE TITLE
Submit Server

### ISSUE THREAD

**Issue by Scypho001** [RevoltSocial/lists#170]
### Server Name

Chillz n hangout

### Server Icon URL

https://autumn.revolt.chat/icons/GioPwLpdxxxo

### Short Server Info

Hiii!!! Welcome, enjoy ur stay, pls read our rules, ty( ꈍᴗꈍ)

### Long Server Info

Hiii, here we talk about basically anything, anime, gaming etc. Anyone is welcomed, enjoy ur stay👍

### Add Tags

Anime, Music, Gaming, Hangout

### Server Owner

8Ball

### Server Owner ID

01FP8QQ7DFDPHBBTJXARZ6CQZ3

### Invite URL

https://app.revolt.chat/invite/8ArHCV8q

**Comment by xMaxximum** [comment]
server icon URL does not exist.
