### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by WhiteClueGaming** [RevoltSocial/lists#173]
### Bot Name

Accord

### Short Explanation

Accord is a fun revolt bot which has images and fun commands
### Long Explanation

Accord is a fun revolt bot which has images and fun commands

### Invite Link

https://app.revolt.chat/bot/01FMMP99YZZJGJ74VFAR1GZ7JH

### Support Link

https://app.revolt.chat/invite/8VX0NmYB

### Bot Icon URL

https://autumn.revolt.chat/avatars/5GCCHH7mTNoBWFYDf70rGwqgNzigsfHE7_jchpEXDN/20211006_101829.png

### Add Tags

Images, Fun

### Owner Name

WhiteClue

### Owner ID

01FMMNXXYM23MT3QSNTK0WWM3T

### Bot ID

01FMMP99YZZJGJ74VFAR1GZ7JH

### Help Command

ac!help

### Bot Prefix

ac!

### Library

revolt.js

**Comment by nerrixDE** [comment]
@WhiteClueGaming The icon needs to be a revolt attachment URL.

**Comment by WhiteClueGaming** [comment]
@nerrixDE I have edited the image link https://autumn.revolt.chat/avatars/5GCCHH7mTNoBWFYDf70rGwqgNzigsfHE7_jchpEXDN/20211006_101829.png

**Comment by nerrixDE** [comment]
@WhiteClueGaming there are no moderation or utility commands

**Comment by WhiteClueGaming** [comment]
@nerrixDE sorry I have removed the Moderation from my bot! I have updated the description

**Comment by nerrixDE** [comment]
@WhiteClueGaming there are no utility commands

**Comment by WhiteClueGaming** [comment]
@nerrixDE done

**Comment by WhiteClueGaming** [comment]
I have changed tags

**Comment by nerrixDE** [comment]
bot not responding
