### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by randomus3rnam3** [RevoltSocial/lists#176]
### Server Name

Speedcubers of Revolt

### Server Icon URL

https://app.revolt.chat/invite/gmkAp4BW

### Short Server Info

People who like cubing

### Long Server Info

Speed cubers of Revolt is for people who speed cubing and like talking about Cubes!!! This is an unofficial cubing server.

### Add Tags

Hangout, Cubing, WCA

### Server Owner

MCRocks323

### Server Owner ID

01FPMRPAJGRJG383F7TN4HPED1

### Invite URL

https://app.revolt.chat/invite/n80e6YeX

**Comment by xMaxximum** [comment]
server icon URL is not valid.

**Comment by randomus3rnam3** [comment]
updated

**Comment by xMaxximum** [comment]
it is a invite and not a URL

**Comment by randomus3rnam3** [comment]
oh
