### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by hodic10** [RevoltSocial/lists#178]
### Server Name

CS|SERVER 🦠

### Server Icon URL

https://www.google.com/url?sa=i&url=https%3A%2F%2F4nite.site%2Fes-419%2Fskins%2Fleviatan-sorbo&psig=AOvVaw39DL5ikoK6MElVoyWGBlwq&ust=1639754819025000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPCPvu7Q6PQCFQAAAAAdAAAAABAD

### Short Server Info

server pequeño en el que puedes unirte y pasar un buen rato ( hay 🍪 )

### Long Server Info

Este es un server crisitano que esta en colab con (Simax y Benebolochu) podeis disfrutar 😋
Puedes contactar al admin para que te de 🍪 pero no tenemos 🥛podrias agregarnos y preguntar a los owners igual ellos tienen 😉 dicho esto que disfrutes 😶‍🌫️ 

Aqui te dejamos las reglas mas vasicas echales un vistazo si tienes dudas consulta soporte o el propio canal.
reglas 📚

- No spam ni nswf 🤬

- No temas de politica 📚

- No pedir roles 👑

                                                                                                                                              Dicho esto disfruta🥰

### Add Tags

!game !social !spam !juegos

### Server Owner

cselhodic10

### Server Owner ID

no se

### Invite URL

https://app.revolt.chat/invite/Pzj37TpB

**Comment by xMaxximum** [comment]
server icon URL needs to be a link from an attachment on revolt. Also please provide a server owner ID by right clicking yourself and copying the ID.

**Comment by hodic10** [comment]
@xMaxximum thanks I posted new issue with the id ( thanks bro )
