### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by ThatOneCalculator** [RevoltSocial/lists#180]
### Bot Name

Among Us Dumpy Bot

### Short Explanation

Makes funny Among Us Dumpy GIFs

### Long Explanation

Port of the Discord bot Among Us Dumpy Bot to Discord. It turns any image into sussy baka twerking crewmates from the hit game Among Us. https://dumpy.t1c.dev

### Invite Link

https://app.revolt.chat/bot/01FQ1AMSEKYQM3Z7ZNJZVQ3DNA

### Bot Icon URL

https://autumn.revolt.chat/avatars/Ciyg3ii2DdYvwhRAYnHq8fOuV595m5xTePpfrKxMwJ/gaydumpy.gif

### Add Tags

Fun, Photo, Gaming

### Owner Name

t1c

### Owner ID

01FF3KESVGH7Z69X85EX9JEP85

### Bot ID

01FQ1AMSEKYQM3Z7ZNJZVQ3DNA

### Help Command

!!help

### Bot Prefix

!!

### Library

revolt.py

**Comment by xMaxximum** [comment]
bot offline

**Comment by ThatOneCalculator** [comment]
Sorry about that. Working out some technical issues. I'll lyk when it's back online for good.
