### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by hodic10** [RevoltSocial/lists#181]
### Server Name

CS|SERVER 🦠

### Server Icon URL

https://autum.revolt.chat/slurp+skin&rlz=1C1CHBF_esES965ES965&sxsrf=AOaemvIzB_-ARPkx2blZ0aDvZ-yjVJe5KQ:1639833589323&source=lnms&tbm=isch&sa=X&ved=2ahUKEwin39OUuO30AhUG4YUKHbL-AvgQ_AUoAXoECAEQAw&biw=1920&bih=969&dpr=1#imgrc=-UvUFYDkxdxpZM&imgdii=vgREZ081Q6f38M

### Short Server Info

server pequeño en el que puedes unirte y pasar un buen rato ( hay 🍪 )

### Long Server Info

Este es un server crisitano que esta en colab con (Simax y Benebolochu) podeis disfrutar 😋
Puedes contactar al admin para que te de 🍪 pero no tenemos 🥛podrias agregarnos y preguntar a los owners igual ellos tienen 😉 dicho esto que disfrutes 😶‍🌫️ 

Aqui te dejamos las reglas mas vasicas echales un vistazo si tienes dudas consulta soporte o el propio canal.
reglas 📚

- No spam ni nswf 🤬

- No temas de politica 📚

- No pedir roles 👑

                                                                                                                                              Dicho esto disfruta🥰

### Add Tags

Juego, Game, Social, Charla, 

### Server Owner

cselhodic10

### Server Owner ID

01FQ11VTFPA2WB08D2FJE46ZSF

### Invite URL

https://app.revolt.chat/invite/fJEKX3Zb

**Comment by xMaxximum** [comment]
the server icon URL is invalid.
