### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by Adithr123** [RevoltSocial/lists#187]
### Server Name

Minekhan

### Server Icon URL

https://autumn.revolt.chat/attachments/8pzyTdjcq5aosFQ-zUbnBFmH-Ft8zBXXS2KiEOBaCy

### Short Server Info

Talk and Play Minekhan! 

### Long Server Info

Interested in Minecraft, but are broke, and cant download fakes? Then this is the server for you! Minehan is a game that was originally coded in khan academy, hence the name but has now expanded to a browser game with constant updates. More info on the server.

### Add Tags

Minecraft, Gaming, Chats

### Server Owner

Avdol

### Server Owner ID

01FQ5CFPE2RG21PY35MHY5BAXK

### Invite URL

https://app.revolt.chat/invite/w2c1VcCw

**Comment by xMaxximum** [comment]
invalid server icon URL

**Comment by Adithr123** [comment]
https://autumn.revolt.chat/attachments/XHRYJfW02-SvNYBQHACXH6XdFoifE_wBJ3g5jB5FAd

**Comment by Adithr123** [comment]
New link : https://autumn.revolt.chat/attachments/XHRYJfW02-SvNYBQHACXH6XdFoifE_wBJ3g5jB5FAd

**Comment by Adithr123** [comment]
https://autumn.revolt.chat/attachments/8pzyTdjcq5aosFQ-zUbnBFmH-Ft8zBXXS2KiEOBaCy
