### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by Chicken-mootle-soup** [RevoltSocial/lists#190]
### Server Name

The fifth floor

### Server Icon URL

https://autumn.revolt.chat/attachments/NEPscMYQHjRq8OhZpTx2gzPN9nO-FI2mJpVKevr3ln/TFF_TAN_FANART.png

### Short Server Info

Mental health server for those who struggle with self harm

### Long Server Info

The fifth floor is a laid back mental health server catering to those with self harm issues.

### Add Tags

Self harm, aspd, mental health, blood, cutting

### Server Owner

Mootykins

### Server Owner ID

01FR161NV7CA33RDY65F5EMQWV

### Invite URL

https://app.revolt.chat/invite/X0AXGnCg

**Comment by nerrixDE** [comment]
hello, @Chicken-mootle-soup looking at the description we currently cannot approve your server. This is about something potential life-dangerous. There are forums on the Internet which have the needed expertice to act correctly in intense situations. We cannot verify that for your server, nor do we want to decide what counts as professional quifications. 

So unfortunatly we cannot approve your server. 

As I'm also Moderator on Revolt, the platform itself, in this role I ask you to not advertise this server with such claims as we see in the submission above. Also you must provide extensive ressources to users to contact, i.e. life Hotlines or links to professional aid. 

If you fail those requirements or we deem your server too dangerous after re-evaluation, we might terminate the server.

Thanks for understanding.
