### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by svqzd** [RevoltSocial/lists#21]
### Bot Name

Purge

### Short Explanation

Purge is an average Revolt bot for most of your needs.

### Long Explanation

You can use Purge for all of your needs. It has moderation, fun, economy, and other things that you may need. It's also open-source and you can submit feature requests on GitHub.

### Invite Link

https://app.revolt.chat/bot/01FE9CH2EWCNPXNM6PQJTKPE31

### Bot Icon URL

https://api.revolt.chat/users/01FE9CH2EWCNPXNM6PQJTKPE31/default_avatar

### Add Tags

moderation, fun, economy, utilities

### Owner Name

coiq

### Owner ID

01FDMYDYGCQF9Y4NJ7HH0KFB5J

### Bot ID

01FE9CH2EWCNPXNM6PQJTKPE31

### Help Command

!help

### Bot Prefix

!

### Library

revolt.js

**Comment by nerrixDE** [comment]
@svqzd invite broke

**Comment by svqzd** [comment]
https://nightly.revolt.chat/bot/01FE9CH2EWCNPXNM6PQJTKPE31

**Comment by nerrixDE** [comment]
still

**Comment by nerrixDE** [comment]
@svqzd bot not responding

**Comment by svqzd** [comment]
im making commands rn aha
