### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by AkiaCode** [RevoltSocial/lists#26]
### Server Name

revolt.rs

### Server Icon URL

Nothing

### Short Server Info

An API wrapper for revolt

### Long Server Info

It is a server that can do various developments, communicate, and talk about APIs related to revolt.

### Add Tags

Develop

### Server Owner

Catry

### Server Owner ID

01FE5M8EQH09W0JNCAHWVPWMDB

### Invite URL

https://app.revolt.chat/invite/k1shCdEH

**Comment by xMaxximum** [comment]
Invite URL not working, closed

**Comment by AkiaCode** [comment]
@xMaxximum k1shCdEH

**Comment by nerrixDE** [comment]
@AkiaCode And you need to provide the server icon url

**Comment by AkiaCode** [comment]
https://user-images.githubusercontent.com/71239005/133751153-bd7ed869-97df-43d7-90a1-30095d46a94a.png
