### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by AkiaCode** [RevoltSocial/lists#27]
### Bot Name

voltre

### Short Explanation

It is a bot that shows various pictures of neko.

### Long Explanation

It shows various neko pictures and provides various other commands while providing other information.

### Invite Link

https://app.revolt.chat/bot/01FEAC4GEHGS0NVHBZPWDFVT24

### Support Link

https://app.revolt.chat/invite/k1shcdeh

### Bot Icon URL

Nothing

### Add Tags

Anime, Utility

### Owner Name

Catry

### Owner ID

01FE5M8EQH09W0JNCAHWVPWMDB

### Bot ID

01FEAC4GEHGS0NVHBZPWDFVT24

### Help Command

/help

### Bot Prefix

/

### Library

revolt.rs

**Comment by xMaxximum** [comment]
bot is offline, and support link doesn't work. Closed.

**Comment by AkiaCode** [comment]
https://user-images.githubusercontent.com/71239005/133751153-bd7ed869-97df-43d7-90a1-30095d46a94a.png

**Comment by AkiaCode** [comment]
> bot is offline, and support link doesn't work. Closed.

https://app.revolt.chat/invite/k1shCdEH

**Comment by nerrixDE** [comment]
bot still off
