### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by elainaaa** [RevoltSocial/lists#34]
### Bot Name

SteveBot

### Short Explanation

Steve is a Revolt Bot designed to show profiles and statistics from the games osu! and Quaver.

### Long Explanation

Steve is a bot developed by Yuyuko (Yu) and Sky (nekogirl). The main purpose is to get osu! and Quaver statistics from the API. This includes profiles, top scores and recent scores. It can currently display all needed data for everything such as rating, rank, accuracy, playcount and much more. It is developed in revoltgo (golang) and uses the osu! and Quaver API to operate.

### Invite Link

https://app.revolt.chat/bot/01FEP6ZHM9NQTQAJ5JVSQ3XHMJ

### Support Link

https://app.revolt.chat/invite/4YAZDkEQ

### Bot Icon URL

https://autumn.revolt.chat/avatars/sXwDw-oN2JfPg8rWAHNhjsSRFzY72T-9orK7-X7QaB?max_side=256

### Add Tags

Quaver, Osu!, Fun

### Owner Name

Yu

### Owner ID

01FENK5NYE2DS1XH8C30QCKMJP

### Bot ID

01FEP6ZHM9NQTQAJ5JVSQ3XHMJ

### Help Command

q!help

### Bot Prefix

q!

### Library

revoltgo

**Comment by nerrixDE** [comment]
@elainaaa Your bot is not responding.

**Comment by elainaaa** [comment]
I just looked into the logs and it seems the channel doesnt exist. Did the bot have access to the channel?
![image](https://user-images.githubusercontent.com/58641892/132134545-f691372c-7cfc-4b1e-9ddd-47122efb3f21.png)

**Comment by elainaaa** [comment]
I've tried running the command a few times and everything seems to work just fine
![image](https://user-images.githubusercontent.com/58641892/132134713-548be5e9-fa07-4839-9d8d-404e1e975932.png)

**Comment by nerrixDE** [comment]
now its working

**Comment by elainaaa** [comment]
Was gibt's? :p

**Comment by nerrixDE** [comment]
"technical issues / GH shenenegains"

**Comment by elainaaa** [comment]
edited :p

**Comment by nerrixDE** [comment]
ty
