### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by Xynnix** [RevoltSocial/lists#37]
### Bot Name

YumekoBot

### Short Explanation

A simple bot with not much but images (nsfw)

### Long Explanation

❯ Images: These all come from one api!
18+ Commands for (18+) content, which will not be named here.
A Dashboard to obtain an api key to set your self up and use the api too!
The api is a custom api that *isnt* nekos.life or nekobot.xyz. So its maintained moderately.

❯ Tools & Info:
`;help`

### Invite Link

https://app.revolt.chat/bot/01FEYFMPWJSJZ0671REAQMP6TY

### Support Link

https://app.revolt.chat/invite/wSq4G1RK

### Bot Icon URL

https://autumn.revolt.chat/avatars/cRsANsyzQ-fxnLRr8MhKgO05aWAQK0XXp93ggQ3OuA/76fbfc827a62d5fd90428bd82457652f.png

### Add Tags

nsfw

### Owner Name

Yumeko

### Owner ID

01FEYFD1WH6YXSD0EHVNFW6VSB

### Bot ID

01FEYFMPWJSJZ0671REAQMP6TY

### Help Command

;help

### Bot Prefix

;

### Library

revolt.js

**Comment by nerrixDE** [comment]
@Xynnix Unfortunately we currently do not list NSFW Bots. Refer to our [Readme](https://github.com/RevoltSocial/lists/blob/main/README.md) for more.
