### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by Andre601** [RevoltSocial/lists#40]
### Server Name

~Nya

### Server Icon URL

https://autumn.revolt.chat/icons/NpWWQFaZOQ6xNFkpXVBm_QSv2pBzngLv8kkdk-RGGT

### Short Server Info

The Revolt version of the original Discord server for the Bot \*Purr*

### Long Server Info

This is the official Revolt server of the original ~Nya Server on Discord, home of the Discord bot \*Purr*.
It is only a casual hangout right now, but may become more in the future... Perhaps even getting a Revolt Bot(?!)

### Add Tags

Chat, Hangout

### Server Owner

Andre_601

### Server Owner ID

01FESEZ18QW9EBMX4VNKMRNZQW

### Invite URL

https://app.revolt.chat/invite/0N7a55jf

**Comment by Andre601** [comment]
You ok?

**Comment by nerrixDE** [comment]
@Andre601 there was a nasty bug I had to fix by re-indexing which causes open/closes
