### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by nixonjoshua98** [RevoltSocial/lists#41]
### Bot Name

SnaccBot

### Short Explanation

General Purpose Utility Bot

### Long Explanation

General purpose utility bot including commands like !xkcd, !waifu, !dog. Will be adding modules including moderator, auto-mod, and more general purpose commands like questionaires and custom member join banners.

### Invite Link

https://app.revolt.chat/bot/01FF67VN38YY7KZ9MTSR9ED2DA

### Support Link

https://app.revolt.chat/invite/eGFXcEwQ

### Bot Icon URL

https://autumn.revolt.chat/avatars/0y8hJvd0aW2_CPM6dp4BIYJWdui3toY9a_GR94M00W

### Add Tags

Anime, Utility, XKCD

### Owner Name

Snaccman

### Owner ID

01FEVXH2CWTC8S87P831MGWHWN

### Bot ID

01FF67VN38YY7KZ9MTSR9ED2DA

### Help Command

s!help

### Bot Prefix

s!

### Library

defectio

**Comment by nerrixDE** [comment]
@nixonjoshua98 your invite link is either invalid or not public

**Comment by nixonjoshua98** [comment]
> @nixonjoshua98 your invite link is either invalid or not public

Sorry! Now public
