### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by jottew** [RevoltSocial/lists#43]
### Bot Name

Rodo

### Short Explanation

Rodo is a bot for todo

### Long Explanation

Rodo is a bot for storing tasks you want to remember for later in a revolt bot

### Invite Link

https://app.revolt.chat/bot/01FFB5Y3QDE8M5CVN42HCN0J8T

### Bot Icon URL

https://autumn.revolt.chat/icons/bHjR3h4OA6Oohd6fovPBbCT_ZC8JFzKY6_jLKrM_lX?max_side=256

### Add Tags

Utility

### Owner Name

jotte

### Owner ID

01FE6JZP6QDH5YKNHATCE0PDVH

### Bot ID

01FFB5Y3QDE8M5CVN42HCN0J8T

### Help Command

rodo help

### Bot Prefix

rodo 

### Library

Defectio

**Comment by nerrixDE** [comment]
@jottew not responding to rodohelp on server

**Comment by jottew** [comment]
> @jottew not responding to rodohelp on server

should be fixed now
