### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by yutetsu** [RevoltSocial/lists#47]
### Server Name

Touhou Revolt

### Server Icon URL

https://autumn.revolt.chat/icons/p4kpzOqG_y8GgqrDPKXdnRer1wJ1Ejbgn2jjimzLja

### Short Server Info

This is a server for people who like Touhou

### Long Server Info

This is a small server for everyone who like Touhou universe.

Users must follow those rules :

- Be respectful to others
- Do not spam or shitpost
- Do not use or create alt account
- No NSFW

### Add Tags

Anime, Gaming, Touhou

### Server Owner

Yutetsudo

### Server Owner ID

01FFG75M0V7K0SFMJF08M7XFX5

### Invite URL

https://app.revolt.chat/invite/q0EJ2jRm

**Comment by yutetsu** [comment]
I dont know if it's a bug, but my server isnt added to the website.

**Comment by nerrixDE** [comment]
> I dont know if it's a bug, but my server isnt added to the website.

odd but true
