### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by MeguminSama** [RevoltSocial/lists#55]
### Server Name

Megumin's Dungeon

### Server Icon URL

https://autumn.revolt.chat/icons/s0BEaNWSqYBNI7nUzEA8UrK13UMBv4_KhEssIbK0qj

### Short Server Info

Server full of people like that hugs

### Long Server Info

Just a quiet place to hang out and chat about stuff like hugs :)

### Add Tags

Anime, Community, Hugs

### Server Owner

Megumin

### Server Owner ID

01FE6S1ADMP5YF9P7B8TB6ZKFH

### Invite URL

https://app.revolt.chat/invite/owo

**Comment by nerrixDE** [comment]
h
