### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by kakerukakadu** [RevoltSocial/lists#67]
### Server Name

KakeruUnion

### Server Icon URL

https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01FD53QCD84PX7D2GBV5SBE09N/01FFTS50ZBQQ0TG2NF3RBJB8GT

### Short Server Info

This is the official fan server for content creator KakeruKakadu

### Long Server Info

If you like socialism/communism or just like me in general it would be nice for you to join our server. The KakeruUnion has a rich history of drama and wars (Discord). This is the official server of Kakeru. Here you can just chill with other fellow comrades and do fun activities together. 

### Add Tags

socialist, communist, official, contentcreator, comradic, 

### Server Owner

KakeruKakadu

### Server Owner ID

https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01FD53QCD84PX7D2GBV5SBE09N/01FFTS50ZBQQ0TG2NF3RBJB8GT

### Invite URL

https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01FD53QCD84PX7D2GBV5SBE09N/01FFTS50ZBQQ0TG2NF3RBJB8GT

**Comment by xMaxximum** [comment]
Server icon URL is not a valid URL, the server owner ID is not a valid ID and the invite URL is not a valid URL either.
