### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by KSPAtlas** [RevoltSocial/lists#70]
### Server Name

fard server

### Server Icon URL

https://autumn.revolt.chat/icons/-RtbxdCsl-FUBgTvVpmcXEW72TvtOnE1_J2n55qIlj

### Short Server Info

mogus

### Long Server Info

fard

### Add Tags

when, the

### Server Owner

KSPAtlas

### Server Owner ID

01FF7DARD6SJ3XC4YM5DEM4823

### Invite URL

https://nightly.revolt.chat/invite/xfWf9b2n

**Comment by xMaxximum** [comment]
Add proper tags first like Community, Anime etc.

**Comment by KSPAtlas** [comment]
I fixed the tags
