### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by every-name-is-taken** [RevoltSocial/lists#72]
### Server Name

All things Ireland! 🇮🇪

### Server Icon URL

https://autumn.revolt.chat/attachments/s-zHCYv9XDQpcO66Dgubiv43IymCyKnkmQOyPUzOP_/originals.jpg

### Short Server Info

A server for all things Ireland related! 🇮🇪

### Long Server Info

**All things Ireland! 🇮🇪**
This server is for Irish people (like myself) and everyone else! We got the usual stuff and the Irish shite!
So come on in and hang out!

### Add Tags

Ireland, Irish, Community, Chill

### Server Owner

toasted_bread

### Server Owner ID

01FFSVYYH3KSB7PB0DMJ4ADT1X

### Invite URL

https://app.revolt.chat/invite/vdBEB11G

**Comment by every-name-is-taken** [comment]
HELP I CANT ADD APPROVED LABEL

**Comment by nerrixDE** [comment]
> HELP I CANT ADD APPROVED LABEL IT WON'T LET ME >:(

Because I need to approve it bruh
