### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by 3317** [RevoltSocial/lists#76]
### Server Name

日本語話者向けコミュニティ

### Server Icon URL

https://autumn.revolt.chat/icons/cek0hYAkDZnbIUxzH70-ZiTJD6IxsUzkyooiBGkfzy

### Short Server Info

日本語話者向けコミュニティです。

### Long Server Info

Revolt の日本語話者向けコミュニティです。
|This is a community for Japanese speakers of Revolt.

日本人の為のものではなく日本語を使える・使いたい人のためのコミュニティです。
|This is a community for people who can and want to use Japanese, not for Japanese people.

### Add Tags

Japan, Japanese, Random, Community

### Server Owner

Sumire_Irozuki

### Server Owner ID

01FG0QDVA40DYKD4Z7VH7H5HVH

### Invite URL

https://app.revolt.chat/invite/4SdxEMAs

**Comment by nerrixDE** [comment]
ok? @3317

**Comment by 3317** [comment]
[DeepL]It looks like there was already a community for Japanese people, so I deleted mine. I didn't look carefully, sorry for the mistake!
#75

**Comment by nerrixDE** [comment]
oh ok
