### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by httpunsecure** [RevoltSocial/lists#80]
### Server Name

Cherry

### Server Icon URL

https://autumn.revolt.chat/icons/X7W8KTX07G_-D1fiUYDpU3FElmQiFtwloNyYvSwNKQ

### Short Server Info

Massive inside joke

### Long Server Info

Talk or worship me or something, I don't know. I'm not your mom.

### Add Tags

Community

### Server Owner

Cherry

### Server Owner ID

01FD8DR857HMBWXKRV15GBMJ17

### Invite URL

https://app.revolt.chat/invite/Cherry

**Comment by httpunsecure** [comment]
Cherry

**Comment by nerrixDE** [comment]
and invalid tags

**Comment by httpunsecure** [comment]
;

**Comment by nerrixDE** [comment]
still
