### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by DuskDoesDev** [RevoltSocial/lists#86]
### Bot Name

KitsuneBot

### Short Explanation

It's a furry bot built to engage users with each other. And to mirror images from various sites.

### Long Explanation

<iframe src="https://leg.fyi/dlabspage.html" class="botlabs_iframe" style="border:0px;"></iframe>

### Invite Link

https://app.revolt.chat/bot/01FF894TXAPVGHAYQZ7A67YR1V

### Support Link

https://app.revolt.chat/invite/m0F5tRqT

### Bot Icon URL

https://autumn.revolt.chat/avatars/ov_UjUsQ_JWWHVTxTAqVAAZiTtrX2BnHN29fp2jaCA/IMG_2950.PNG

### Add Tags

furry, anime, weeb, funny, memes, e621, yiff, hentai, r34

### Owner Name

Kitsune

### Owner ID

01FDF6KSQY4KP6XS8931A6ACSY

### Bot ID

01FF894TXAPVGHAYQZ7A67YR1V

### Help Command

$help

### Bot Prefix

$

### Library

revolt.js

**Comment by nerrixDE** [comment]
@DuskDoesDev only plain text in long desc allowed

**Comment by DuskDoesDev** [comment]
This is so sad. Now I have to reformat things :death:
