### ISSUE TITLE
Bot Submission

### ISSUE THREAD

**Issue by Danixd12** [RevoltSocial/lists#97]
### Bot Name

Mc Skins

### Short Explanation

Mc Skins provides you a new way to view minecraft users information

### Long Explanation

Mc Skins is here to provide you of information about minecraft users such as their skin, head, names, etc. Its currently in active development and I will try to update it every day.

### Invite Link

https://app.revolt.chat/bot/01FGNDE5TPH2N0N6N7J1T7WARZ

### Support Link

https://app.revolt.chat/invite/ZqFb7gzs

### Bot Icon URL

https://autumn.revolt.chat/avatars/gxnSa2ALyarUSgwklHDJUeylMyCS3F6uXNYUBIWlMI/OIP%20(3).jfif

### Add Tags

Utility, Minecraft, Fun

### Owner Name

dani33y

### Owner ID

01FGHS6Y99MZ959RAEG5YG5DQ3

### Bot ID

01FGNDE5TPH2N0N6N7J1T7WARZ

### Help Command

mc-help

### Bot Prefix

mc-

### Library

revolt.js

**Comment by nerrixDE** [comment]
@Danixd12 invite not working

**Comment by nerrixDE** [comment]
bot offline
