### ISSUE TITLE
Server Submission

### ISSUE THREAD

**Issue by Fireentr** [RevoltSocial/lists#98]
### Server Name

Nova

### Server Icon URL

https://autumn.revolt.chat/attachments/03vVFSXQWxrYxA8kN8g4jPKu8U0YaobDkthc7774du/935e6fd262bda29d7516d682b8dd1ba7.png

### Short Server Info

Nova is a minecraft pvp client for 1.8, made with visuals in mind. Currently in Beta.

### Long Server Info

Nova is a minecraft pvp client for 1.8, made with visuals in mind.
We are currently in closed beta.

You can read more at: https://novaclient.club/

### Add Tags

Minecraft, Mod, Client, Gaming

### Server Owner

Ralsei

### Server Owner ID

01FF3B604W9VYPE6Y558EGNK4H

### Invite URL

https://app.revolt.chat/invite/3ec4mT4f

**Comment by nerrixDE** [comment]
the server icon url is 404 @Fireentr

**Comment by Fireentr** [comment]
oops, heres another link: https://files.catbox.moe/j9jdci.png

**Comment by nerrixDE** [comment]
@Fireentr can you upload it as an ttachment to revolt and use an revolt CDN url?
